export const dummyData = {
  key: "User",
  value: "Customized_Object",
  type: "Object",
  children: {
    xyz: {
      key: "User_name",
      value: "Customized_Object",
      type: "Object",
      children: {
        xyz: {
          key: "post",
          value: "Customized_Array",
          type: "Array",
          children: {
            gggerr: {
              key: "Uni",
              value: "String",
              type: "String",
              children: {},
              counter: 3,
              copiesOfChildren: 0,
              isOpen: true,
            },
          },
          counter: 2,
          copiesOfChildren: 0,
          isOpen: true,
        },
      },
      counter: 1,
      copiesOfChildren: 0,
      isOpen: true,
    },
    ggg: {
      key: "User_name",
      value: "String",
      type: "String",
      children: {},
      counter: 1,
      copiesOfChildren: 0,
      isOpen: true,
    },
    greregg: {
      key: "Urrrr",
      value: "Object",
      type: "Object",
      children: {},
      counter: 1,
      copiesOfChildren: 0,
      isOpen: true,
    },
  },
  counter: 0,
  copiesOfChildren: 1,
  isOpen: true,
};
